# Generated by Django 3.2.6 on 2022-06-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0002_alter_grocery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
