# Generated by Django 3.2.6 on 2022-06-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0003_alter_grocery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='description',
            field=models.TextField(),
        ),
    ]
